Repository OPCODE-Open-Spring-Fest/KeyLogger5155, pull requests merged in 2024-04, with the labels that each got.

#9 feat: Removed pywin32 dependency & cross platform support
  app/guikeylogger.py
Labels: PR:Accept, Semver:major, Type:Medium

#12 ci: update readme
  README.md
Labels: PR:Accept, Semver:minor, Type:Medium

#13 Revert "ci: update readme"
  README.md
Labels: PR:Accept, Semver:minor, Type:Easy

#14 removal of requests dependency
  app/guikeylogger.py
  app/requirements.txt
Labels: PR:Accept, Semver:major, Type:Medium
